### ISSUE TITLE
what should we call the segments of dwyl ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#51]
What should we call the "_segments_" of the dwyl activities?
At present @iteles is referring to them as "branches" see: https://github.com/dwyl/phase-two/pull/50/files#r105893978 but we think there _could_ be a _clearer_ way of describing them...

**Comment by markwilliamfirth** [comment]
Please could you explain the reason for this being created as an issue? The comment [here](https://github.com/dwyl/phase-two/pull/50#discussion_r106096353) suggested to me that you didn't think we should discuss nomenclature

**Comment by iteles** [comment]
@markwilliamfirth The section you're referring to is around the dwyl brand name where we already have a name that has been in use and there is already an issue open on it here: https://github.com/dwyl/hq/issues/249 (to be fair, as I said in that discussion, it's legacy, I don't think there's a discussion there, I totally agree with you).

This is simply opening a similar discussion on wording we haven't actually started using yet along a similar vein. :blush:

Note there's no priority label here, it's just opening it up for anyone who has a good idea to drop in a quick comment and input because the three suggestions we have come up with: 'branches', 'verticals' and 'arms' haven't really felt right. If there *are* none, I'll make a call, we'll close this issue and then someone can open another if they take issue with the name 👍

**Comment by markwilliamfirth** [comment]
>Our sole focus for the next 6 months is to make sure we are cashflow positive (i.e. not burn through our hard-earned capital) not to argue about names or other details that users don't care about.

Is the basis for an argument that directly contrasts with the intention of opening this issue so I'm trying to understand the reasoning here.

**Comment by nelsonic** [comment]
@markwilliamfirth agreed. 👍 
Closing to focus on coding. 🤐 
Thanks! 🎉
